### ISSUE TITLE
Add check to ensure multiple trees are available for ERC_analysis.py 

### ISSUE THREAD

**Issue by tgattsIV** [EvanForsythe/ERCnet#44]

**Comment by tgattsIV** [comment]
@EvanForsythe Hey, do you remember what this was about or what the issue was? I'd like to write down what the problem and potential solution would be so that when we finally get around to solving it we've got at least a jumping off point.

**Comment by EvanForsythe** [comment]
I have a two guesses about what this one is about about...
(1) Either we encountered a run where something upstream had broken, resulting in 0 input files being passed to the R-script (which is always annoying because it's hard to get error messages back from R.
(2) Or we ran the while analysis with -t = 1 at the phylogenomics stage. If would perform the whole pipeline on one tree, which should work all the way up until the ERC analysis step because that step requires pairs of trees to compare. 

I would recommend put safe-guards against both types of errors while we're at it. 

For #1 we should check for the existence of at least one file in DLCpar/ that contains the string "_NODES_BL.txt.dlcpar.locus.recon". This check should occur before calling R (line 88 currently in ERC_analysese.py).

For #2 we should check to make sure the length of BLs['HOG_ID'] is at least 2. This check should occur before we generate a list of pairwise combinations (line 120 currently).
